spring:
  application:
    name: cs544-project-service
  datasource:
    url: jdbc:sqlserver://cs544.cs.miu.edu:1433;databaseName=CS544-202303-01;encrypt=true;trustServerCertificate=true;
    username: CS544-202303-01
    password: 2e0d170b-5a3a-4076-a006-2a7977bf8ce9
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2016Dialect
logging:
  file:
    name: /Coding/Logging/${spring.application.name}/log
    